//! Plan 03-03 Task 3 integration tests for deal-lsp.
//!
//! Drives the `Backend` through tower-lsp's `LspService` so the full
//! request → server → client pipeline is exercised. The ClientSocket
//! receiver is drained on a background task into a shared notifications
//! Vec; tests assert against that collected stream after performing the
//! relevant LSP request.
//!
//! Three required tests (one per `<behavior>` bullet in 03-03-PLAN.md):
//!
//! 1. `diagnostics_match_phase_2_codes` — open a malformed showcase file;
//!    assert publishDiagnostics arrives carrying ≥1 E-code from the
//!    Phase 2 envelope (D-32 / D-33).
//!
//! 2. `format_round_trip` — open the canonical battery.deal showcase
//!    file; send textDocument/formatting; assert returned TextEdit.new_text
//!    equals the committed golden byte-for-byte (Issue 6 — golden was
//!    generated by `deal fmt --stdout` BEFORE this test runs; the test
//!    is a regression detector, not an in-test recomputation).
//!
//! 3. `debounce_collapses_rapid_changes` — open a file, fire 5 did_change
//!    events at sub-100ms intervals, then wait past the 300ms debounce
//!    window; assert exactly two parses ran (1 for open, 1 for the
//!    coalesced re-parse).
//!
//! NOTE on showcase path: Plan 03-03-PLAN.md references
//! `tests/showcase/sedan_project/vehicle/electrical/BatteryPack.deal`,
//! which does NOT exist in this repo (Rule 3 deviation). The closest
//! match — and the canonical showcase battery model — is
//! `spec/examples/showcase/packages/vehicle/battery.deal`. Documented
//! in the Plan SUMMARY as deviation; downstream Plan 03-04 / 03-07 work
//! references this file already.

use std::time::Duration;

use deal_lsp::{Backend, Documents, Index, DEBOUNCE_MS};
use futures::StreamExt;
use std::sync::Arc;
use tokio::sync::Mutex;
use tower::Service;
use tower_lsp::jsonrpc::{Request as JsonRpcRequest, Response as JsonRpcResponse};
use tower_lsp::lsp_types::*;
use tower_lsp::LspService;

/// Path to the showcase battery.deal file (substituted for the
/// non-existent BatteryPack.deal cited in PLAN.md — see file header).
const SHOWCASE_BATTERY: &str = "../spec/examples/showcase/packages/vehicle/battery.deal";

/// Path to a known-malformed file producing E2100 codes.
const MALFORMED_SAMPLE: &str = "../tests/malformed/m01_missing_semicolon.deal";

/// Path to the showcase root (mounted via tests/showcase symlink to
/// ../spec/examples/showcase). Used as the LSP workspace folder for
/// the Plan 04 eager_parse + cross-file go-to-definition tests.
const SHOWCASE_ROOT: &str = "../spec/examples/showcase";

/// Path to the interfaces file that defines ThermallyManaged — the
/// cross-file definition target for `definition_lookup_specializes`.
/// Held as a reference constant; the test does not need to `did_open`
/// this file because the eager_parse spawned from `initialized`
/// populates the index for all workspace files automatically.
#[allow(dead_code)]
const SHOWCASE_THERMAL: &str = "../spec/examples/showcase/packages/interfaces/thermal.deal";

/// Committed golden output of `deal fmt --stdout SHOWCASE_BATTERY`.
/// Generated once by the executor during Task 3 and committed to git.
const GOLDEN_FORMATTED: &str = include_str!("golden/formatted/battery.deal.expected");

/// Committed golden output of `cargo run -p deal-lsp --bin deal-lsp-gen-golden`
/// (Plan 03-04 Task 3 / Issue 6). Read at compile time; the test does
/// byte equality on the `data` field after normalising `result_id`.
const GOLDEN_SEMANTIC_TOKENS: &str =
    include_str!("golden/semantic_tokens/BatteryPack.deal.expected.json");

/// Collected notifications (publishDiagnostics + other server-to-client
/// messages) from the LspService's ClientSocket.
type NotificationSink = Arc<Mutex<Vec<JsonRpcRequest>>>;

/// Spawn the LspService and drain ClientSocket on a background task.
/// Returns the service handle (for sending requests) and the shared
/// notification sink.
async fn spawn_service() -> (
    LspService<Backend>,
    Arc<Documents>,
    NotificationSink,
) {
    let (service, _docs, _idx, sink) = spawn_service_full().await;
    (service, _docs, sink)
}

/// Like `spawn_service` but also surfaces the Index so Plan 04 tests
/// can observe in-memory symbol-table state.
async fn spawn_service_full() -> (
    LspService<Backend>,
    Arc<Documents>,
    Arc<Index>,
    NotificationSink,
) {
    let (service, socket) = LspService::new(Backend::new);
    // Snapshot the Documents + Index Arcs so tests can introspect.
    let documents = service.inner().documents.clone();
    let index = service.inner().index.clone();

    let notifications: NotificationSink = Arc::new(Mutex::new(Vec::new()));
    {
        let sink = notifications.clone();
        tokio::spawn(async move {
            let mut socket = socket;
            while let Some(req) = socket.next().await {
                sink.lock().await.push(req);
            }
        });
    }

    (service, documents, index, notifications)
}

/// Send `initialize` so the server transitions to Initialized state
/// (otherwise tower-lsp rejects subsequent requests with "server not
/// initialized" responses).
async fn initialize(service: &mut LspService<Backend>) {
    initialize_with_root(service, None).await;
}

/// Like `initialize` but declares a workspace folder root URI so the
/// `initialized` handler kicks off the eager_parse background task
/// (Plan 03-04 Task 1).
async fn initialize_with_root(service: &mut LspService<Backend>, root: Option<&str>) {
    let workspace_folders = root.map(|p| {
        let abs = std::fs::canonicalize(p).expect("workspace root canonicalize");
        let uri = Url::from_file_path(&abs).expect("workspace folder URL");
        vec![WorkspaceFolder {
            uri,
            name: "showcase".to_string(),
        }]
    });
    let init_req = JsonRpcRequest::build("initialize")
        .id(1)
        .params(
            serde_json::to_value(InitializeParams {
                capabilities: ClientCapabilities::default(),
                workspace_folders,
                ..Default::default()
            })
            .unwrap(),
        )
        .finish();
    let _: Option<JsonRpcResponse> = service.call(init_req).await.unwrap();

    let initialized_req = JsonRpcRequest::build("initialized")
        .params(serde_json::to_value(InitializedParams {}).unwrap())
        .finish();
    let _: Option<JsonRpcResponse> = service.call(initialized_req).await.unwrap();
}

async fn did_open(service: &mut LspService<Backend>, uri: &Url, text: &str, version: i32) {
    let params = DidOpenTextDocumentParams {
        text_document: TextDocumentItem {
            uri: uri.clone(),
            language_id: "deal".to_string(),
            version,
            text: text.to_string(),
        },
    };
    let req = JsonRpcRequest::build("textDocument/didOpen")
        .params(serde_json::to_value(params).unwrap())
        .finish();
    let _: Option<JsonRpcResponse> = service.call(req).await.unwrap();
}

async fn did_change(
    service: &mut LspService<Backend>,
    uri: &Url,
    text: &str,
    version: i32,
) {
    let params = DidChangeTextDocumentParams {
        text_document: VersionedTextDocumentIdentifier {
            uri: uri.clone(),
            version,
        },
        content_changes: vec![TextDocumentContentChangeEvent {
            range: None,
            range_length: None,
            text: text.to_string(),
        }],
    };
    let req = JsonRpcRequest::build("textDocument/didChange")
        .params(serde_json::to_value(params).unwrap())
        .finish();
    let _: Option<JsonRpcResponse> = service.call(req).await.unwrap();
}

async fn formatting(service: &mut LspService<Backend>, uri: &Url) -> Option<Vec<TextEdit>> {
    let params = DocumentFormattingParams {
        text_document: TextDocumentIdentifier { uri: uri.clone() },
        options: FormattingOptions {
            tab_size: 4,
            insert_spaces: true,
            ..Default::default()
        },
        work_done_progress_params: Default::default(),
    };
    let req = JsonRpcRequest::build("textDocument/formatting")
        .id(99)
        .params(serde_json::to_value(params).unwrap())
        .finish();
    let resp = service.call(req).await.unwrap().expect("formatting returned None response");
    // resp.result() returns Option<&Value>; decode to Option<Vec<TextEdit>>.
    let (_id, result) = resp.into_parts();
    let value = result.expect("formatting response had no result");
    serde_json::from_value(value).expect("formatting result deserialise failed")
}

/// Helper: find all publishDiagnostics notifications in the sink.
async fn collected_diagnostics(sink: &NotificationSink) -> Vec<PublishDiagnosticsParams> {
    let mut out = Vec::new();
    for req in sink.lock().await.iter() {
        if req.method() == "textDocument/publishDiagnostics" {
            if let Some(params) = req.params() {
                if let Ok(p) =
                    serde_json::from_value::<PublishDiagnosticsParams>(params.clone())
                {
                    out.push(p);
                }
            }
        }
    }
    out
}

// ---------------------------------------------------------------------
// Test 1: diagnostics_match_phase_2_codes
// ---------------------------------------------------------------------

#[tokio::test]
async fn diagnostics_match_phase_2_codes() {
    let (mut service, _docs, sink) = spawn_service().await;
    initialize(&mut service).await;

    let src = std::fs::read_to_string(MALFORMED_SAMPLE)
        .expect("malformed sample missing");
    let uri = Url::from_file_path(std::fs::canonicalize(MALFORMED_SAMPLE).unwrap())
        .expect("file:// URL build");

    did_open(&mut service, &uri, &src, 1).await;
    // Give the background sink task a moment to drain the notification.
    tokio::time::sleep(Duration::from_millis(50)).await;

    let pubs = collected_diagnostics(&sink).await;
    assert!(
        !pubs.is_empty(),
        "expected ≥1 publishDiagnostics notification after did_open"
    );
    let last = pubs.last().unwrap();
    assert_eq!(last.uri, uri);
    assert!(
        !last.diagnostics.is_empty(),
        "expected ≥1 diagnostic for malformed sample"
    );
    // Phase 2 envelope codes start with 'E' (E0xxx parser, E2xxx sema).
    let code_strs: Vec<String> = last
        .diagnostics
        .iter()
        .filter_map(|d| match &d.code {
            Some(NumberOrString::String(s)) => Some(s.clone()),
            _ => None,
        })
        .collect();
    assert!(
        code_strs.iter().any(|c| c.starts_with('E')),
        "expected at least one E-code diagnostic, got {code_strs:?}"
    );
    // Sema-level error E2100 is the expected code for this fixture
    // (verified live via dump_probe in Task 3).
    assert!(
        code_strs.iter().any(|c| c == "E2100"),
        "expected E2100 (sema undefined type) for m01 fixture, got {code_strs:?}"
    );
    // Source field must identify deal-lsp (so VS Code groups them).
    assert_eq!(last.diagnostics[0].source.as_deref(), Some("deal-lsp"));
    // Severity for the E2100 entries is ERROR.
    let has_error = last
        .diagnostics
        .iter()
        .any(|d| d.severity == Some(DiagnosticSeverity::ERROR));
    assert!(has_error, "expected at least one ERROR-severity diagnostic");
}

// ---------------------------------------------------------------------
// Test 2: format_round_trip
// ---------------------------------------------------------------------

#[tokio::test]
async fn format_round_trip() {
    let (mut service, _docs, _sink) = spawn_service().await;
    initialize(&mut service).await;

    let src = std::fs::read_to_string(SHOWCASE_BATTERY)
        .expect("showcase battery.deal missing");
    let uri = Url::from_file_path(std::fs::canonicalize(SHOWCASE_BATTERY).unwrap())
        .expect("file:// URL build");

    did_open(&mut service, &uri, &src, 1).await;

    let edits = formatting(&mut service, &uri)
        .await
        .expect("formatting returned None for valid file");
    assert_eq!(edits.len(), 1, "expected exactly one TextEdit covering full document");

    // Byte-for-byte regression check against the committed golden.
    // If this fails: regenerate via
    //   ./target/release/deal fmt --stdout spec/examples/showcase/packages/vehicle/battery.deal \
    //     > lsp/tests/golden/formatted/battery.deal.expected
    // and re-commit. The golden is intentionally produced by the CLI
    // (an independent codepath) so the test is not a tautology
    // (Plan 03-03 Issue 6 resolution).
    assert_eq!(
        edits[0].new_text.as_bytes(),
        GOLDEN_FORMATTED.as_bytes(),
        "format_round_trip: LSP formatter output diverged from committed golden"
    );
}

// ---------------------------------------------------------------------
// Test 3: debounce_collapses_rapid_changes
// ---------------------------------------------------------------------

#[tokio::test]
async fn debounce_collapses_rapid_changes() {
    let (mut service, documents, _sink) = spawn_service().await;
    initialize(&mut service).await;

    // Synthetic in-memory source (no fs dependency).
    let uri = Url::parse("file:///debounce.deal").unwrap();
    did_open(&mut service, &uri, "package debounce;", 1).await;
    let parses_after_open = documents.parse_count();
    assert_eq!(parses_after_open, 1, "did_open should trigger exactly one parse");

    // Fire 5 did_change events within the debounce window (300ms).
    for v in 2i32..=6 {
        did_change(
            &mut service,
            &uri,
            &format!("package debounce; // v{v}"),
            v,
        )
        .await;
        tokio::time::sleep(Duration::from_millis(30)).await;
    }
    // None of the 5 should have fired yet (only ~120ms elapsed).
    let parses_mid_burst = documents.parse_count();
    assert_eq!(
        parses_mid_burst, 1,
        "expected 0 debounced parses during burst, got {} extra",
        parses_mid_burst - 1
    );

    // Wait comfortably past the debounce window.
    tokio::time::sleep(Duration::from_millis(DEBOUNCE_MS + 100)).await;
    let parses_after_debounce = documents.parse_count();
    assert_eq!(
        parses_after_debounce, 2,
        "expected exactly one coalesced re-parse after debounce (open=1 + debounced=1), got {parses_after_debounce}"
    );
}

// =====================================================================
// Plan 03-04 integration tests (5 new — bringing total to 8 per
// RESEARCH §1056). All exercise the providers + workspace index that
// Tasks 1–3 of Plan 04 wired up.
// =====================================================================

/// Helper: send a typed LSP request and decode the result into `T`.
async fn call_request<T: serde::de::DeserializeOwned>(
    service: &mut LspService<Backend>,
    method: &'static str,
    id: i64,
    params: impl serde::Serialize,
) -> T {
    let req = JsonRpcRequest::build(method)
        .id(id)
        .params(serde_json::to_value(params).unwrap())
        .finish();
    let resp = service
        .call(req)
        .await
        .unwrap()
        .unwrap_or_else(|| panic!("{method} returned no response"));
    let (_id, result) = resp.into_parts();
    let value = result
        .unwrap_or_else(|e| panic!("{method} response had error: {e:?}"));
    serde_json::from_value(value).unwrap_or_else(|e| {
        panic!("{method} result deserialise failed: {e}")
    })
}

/// Helper: poll `index.len()` until ≥ `threshold` or `timeout` elapses.
/// Returns the final len (so the caller can include it in failure msgs).
async fn wait_for_index(index: &Index, threshold: usize, timeout: Duration) -> usize {
    let start = std::time::Instant::now();
    while start.elapsed() < timeout {
        let n = index.len();
        if n >= threshold {
            return n;
        }
        tokio::time::sleep(Duration::from_millis(100)).await;
    }
    index.len()
}

// ---------------------------------------------------------------------
// Test 4: completion_returns_element_keywords
// ---------------------------------------------------------------------

#[tokio::test]
async fn completion_returns_element_keywords() {
    let (mut service, _docs, index, _sink) = spawn_service_full().await;
    initialize_with_root(&mut service, Some(SHOWCASE_ROOT)).await;
    // Wait for eager_parse so workspace types are available in Group 2.
    let _ = wait_for_index(&index, 20, Duration::from_secs(5)).await;

    let src = std::fs::read_to_string(SHOWCASE_BATTERY).expect("battery.deal");
    let uri = Url::from_file_path(std::fs::canonicalize(SHOWCASE_BATTERY).unwrap())
        .expect("URL");
    did_open(&mut service, &uri, &src, 1).await;
    tokio::time::sleep(Duration::from_millis(50)).await;

    let params = CompletionParams {
        text_document_position: TextDocumentPositionParams {
            text_document: TextDocumentIdentifier { uri: uri.clone() },
            position: Position::new(0, 0),
        },
        work_done_progress_params: WorkDoneProgressParams::default(),
        partial_result_params: PartialResultParams::default(),
        context: None,
    };
    let resp: CompletionResponse =
        call_request(&mut service, "textDocument/completion", 10, params).await;
    let items = match resp {
        CompletionResponse::Array(a) => a,
        CompletionResponse::List(l) => l.items,
    };

    // Assert all 11 element keywords are present as KEYWORD-kind items.
    let kw_labels: Vec<String> = items
        .iter()
        .filter(|i| i.kind == Some(CompletionItemKind::KEYWORD))
        .map(|i| i.label.clone())
        .collect();
    for expected in &[
        "part def", "port def", "action def", "state def", "requirement def",
        "constraint def", "attribute def", "item def", "interface def",
        "connection def", "flow def",
    ] {
        assert!(
            kw_labels.iter().any(|l| l == expected),
            "missing element keyword {expected} (have: {kw_labels:?})"
        );
    }
    assert_eq!(kw_labels.len(), 11, "expected 11 element-keyword items");

    // Assert ≥3 workspace-type candidates surface as CLASS items.
    let class_items: Vec<&CompletionItem> = items
        .iter()
        .filter(|i| i.kind == Some(CompletionItemKind::CLASS))
        .collect();
    assert!(
        class_items.len() >= 3,
        "expected ≥3 workspace-type completion items, got {} (index.len = {})",
        class_items.len(),
        index.len()
    );
}

// ---------------------------------------------------------------------
// Test 5: definition_lookup_specializes
// ---------------------------------------------------------------------

#[tokio::test]
async fn definition_lookup_specializes() {
    let (mut service, _docs, index, _sink) = spawn_service_full().await;
    initialize_with_root(&mut service, Some(SHOWCASE_ROOT)).await;
    // Wait for eager_parse to populate the cross-file index.
    let n = wait_for_index(&index, 20, Duration::from_secs(5)).await;
    assert!(
        n >= 10,
        "eager_parse did not populate the index within 5s (got {n} symbols)"
    );

    // Open battery.deal — the file containing `<<specializes>> ThermallyManaged`.
    let src = std::fs::read_to_string(SHOWCASE_BATTERY).expect("battery.deal");
    let uri = Url::from_file_path(std::fs::canonicalize(SHOWCASE_BATTERY).unwrap())
        .unwrap();
    did_open(&mut service, &uri, &src, 1).await;
    tokio::time::sleep(Duration::from_millis(50)).await;

    // Locate the byte offset of "ThermallyManaged" in the
    // <<specializes>> clause. battery.deal mentions the type twice —
    // once in the `import` statement and once as the specializes
    // referent — we want the SECOND occurrence (the reference site).
    let needle = "ThermallyManaged";
    let first = src.find(needle).expect("ThermallyManaged in battery.deal");
    let byte = src[first + needle.len()..]
        .find(needle)
        .map(|n| first + needle.len() + n)
        .expect("second ThermallyManaged (the <<specializes>> referent)");
    let (line, char_) = byte_to_line_char(&src, byte + 4); // mid-identifier

    let params = GotoDefinitionParams {
        text_document_position_params: TextDocumentPositionParams {
            text_document: TextDocumentIdentifier { uri: uri.clone() },
            position: Position::new(line, char_),
        },
        work_done_progress_params: WorkDoneProgressParams::default(),
        partial_result_params: PartialResultParams::default(),
    };
    let resp: GotoDefinitionResponse = call_request_optional(
        &mut service,
        "textDocument/definition",
        11,
        params,
    )
    .await
    .expect(
        "textDocument/definition returned null — index lookup miss for \
         ThermallyManaged. Likely cause: eager_parse incomplete OR \
         AST candidate extraction returned None.",
    );
    let loc = match resp {
        GotoDefinitionResponse::Scalar(l) => l,
        GotoDefinitionResponse::Array(mut v) => v.pop().expect("non-empty array"),
        GotoDefinitionResponse::Link(_) => panic!("unexpected Link variant"),
    };
    // Cross-file go-to-definition: the target uri must NOT be battery.deal —
    // ThermallyManaged is defined in interfaces/thermal.deal.
    let target_path = loc.uri.to_file_path().expect("file:// URI");
    assert!(
        target_path.ends_with("interfaces/thermal.deal"),
        "expected cross-file target interfaces/thermal.deal, got {}",
        target_path.display()
    );
    // Range must be inside the target file (not empty / not bogus).
    assert!(
        loc.range.end.line >= loc.range.start.line,
        "target range is malformed: {:?}",
        loc.range
    );
}

// ---------------------------------------------------------------------
// Test 6: hover_renders_jsdoc
// ---------------------------------------------------------------------

#[tokio::test]
async fn hover_renders_jsdoc() {
    let (mut service, _docs, _idx, _sink) = spawn_service_full().await;
    initialize(&mut service).await;

    let src = std::fs::read_to_string(SHOWCASE_BATTERY).expect("battery.deal");
    let uri = Url::from_file_path(std::fs::canonicalize(SHOWCASE_BATTERY).unwrap())
        .unwrap();
    did_open(&mut service, &uri, &src, 1).await;
    tokio::time::sleep(Duration::from_millis(50)).await;

    // battery.deal line 22 (0-based 21): `part def BatteryCell {` — has a
    // /** ... */ doc comment immediately above it covering "Individual
    // lithium-ion pouch cell." Hover on "BatteryCell" identifier.
    let needle = "part def BatteryCell";
    let byte = src.find(needle).expect("BatteryCell declaration in battery.deal");
    // Position cursor INSIDE the part_def span (e.g. on "def").
    let (line, char_) = byte_to_line_char(&src, byte + 5);

    let params = HoverParams {
        text_document_position_params: TextDocumentPositionParams {
            text_document: TextDocumentIdentifier { uri: uri.clone() },
            position: Position::new(line, char_),
        },
        work_done_progress_params: WorkDoneProgressParams::default(),
    };
    let resp: Option<Hover> = call_request_optional(
        &mut service,
        "textDocument/hover",
        12,
        params,
    )
    .await;
    let hover = resp.expect("hover returned None for documented declaration");
    let markup = match hover.contents {
        HoverContents::Markup(m) => m,
        _ => panic!("expected Markup hover contents"),
    };
    assert_eq!(markup.kind, MarkupKind::Markdown);
    assert!(
        markup.value.contains("Individual lithium-ion pouch cell"),
        "hover markup missing expected doc text; got: {:?}",
        markup.value
    );
}

// ---------------------------------------------------------------------
// Test 7: semantic_tokens_match_golden
// ---------------------------------------------------------------------

#[tokio::test]
async fn semantic_tokens_match_golden() {
    let (mut service, _docs, _idx, _sink) = spawn_service_full().await;
    initialize(&mut service).await;

    let src = std::fs::read_to_string(SHOWCASE_BATTERY).expect("battery.deal");
    let uri = Url::from_file_path(std::fs::canonicalize(SHOWCASE_BATTERY).unwrap())
        .unwrap();
    did_open(&mut service, &uri, &src, 1).await;
    tokio::time::sleep(Duration::from_millis(50)).await;

    let params = SemanticTokensParams {
        text_document: TextDocumentIdentifier { uri: uri.clone() },
        work_done_progress_params: WorkDoneProgressParams::default(),
        partial_result_params: PartialResultParams::default(),
    };
    let resp: SemanticTokensResult =
        call_request(&mut service, "textDocument/semanticTokens/full", 13, params)
            .await;
    let actual = match resp {
        SemanticTokensResult::Tokens(t) => t,
        SemanticTokensResult::Partial(_) => panic!("expected Tokens variant"),
    };

    // Issue 6 resolution: parse the committed golden via serde_json and
    // compare only the `data` field byte-for-byte. result_id differs
    // (golden: "golden"; runtime: per-session UUID) — normalize away.
    let golden: SemanticTokens =
        serde_json::from_str(GOLDEN_SEMANTIC_TOKENS).expect("golden JSON parse");
    assert_eq!(
        actual.data, golden.data,
        "semantic-tokens data drift — regenerate via: \
         cargo run --release -p deal-lsp --bin deal-lsp-gen-golden -- \
         tests/showcase/packages/vehicle/battery.deal \
         lsp/tests/golden/semantic_tokens/BatteryPack.deal.expected.json \
         and re-commit the golden file (Issue 6 — no inline env-var \
         escape hatch in this test source)."
    );
}

// ---------------------------------------------------------------------
// Test 8: workspace_index_populated_after_initialize
// ---------------------------------------------------------------------

#[tokio::test]
async fn workspace_index_populated_after_initialize() {
    let (mut service, _docs, index, _sink) = spawn_service_full().await;
    initialize_with_root(&mut service, Some(SHOWCASE_ROOT)).await;

    // Poll up to 5s for the eager_parse background task to finish.
    // Threshold: the showcase has 19 .deal/.dealx files producing ≥40
    // FQ-path entries (measured empirically: 48 at the time of authoring).
    // We use 40 to leave headroom for showcase-edit drift while still
    // proving eager_parse actually executed (not just spun up).
    let n = wait_for_index(&index, 40, Duration::from_secs(5)).await;
    assert!(
        n >= 40,
        "eager_parse should populate ≥40 symbols on the showcase, got {n}"
    );
    // Spot-check: ThermallyManaged + BatteryPack are showcase staples;
    // they must be in the in-memory index under SOME PathString. The
    // exact prefix depends on which file declared which `package`
    // statement — we accept any path whose suffix matches the type name.
    let snap = index.snapshot();
    let paths: Vec<String> = snap.iter().map(|(p, _)| p.clone()).collect();
    let has_suffix = |needle: &str| -> bool {
        paths
            .iter()
            .any(|p| p == needle || p.ends_with(&format!(".{needle}")))
    };
    assert!(
        has_suffix("ThermallyManaged"),
        "expected an index entry ending in .ThermallyManaged. Top paths: {:?}",
        &paths[..paths.len().min(10)]
    );
    assert!(
        has_suffix("BatteryPack"),
        "expected an index entry ending in .BatteryPack. Top paths: {:?}",
        &paths[..paths.len().min(10)]
    );
}

// ---------------------------------------------------------------------
// Helpers used by the 5 Plan 04 tests above
// ---------------------------------------------------------------------

/// Helper for requests whose result type is `Option<T>` (e.g. hover).
async fn call_request_optional<T: serde::de::DeserializeOwned>(
    service: &mut LspService<Backend>,
    method: &'static str,
    id: i64,
    params: impl serde::Serialize,
) -> Option<T> {
    let req = JsonRpcRequest::build(method)
        .id(id)
        .params(serde_json::to_value(params).unwrap())
        .finish();
    let resp = service
        .call(req)
        .await
        .unwrap()
        .unwrap_or_else(|| panic!("{method} returned no response"));
    let (_id, result) = resp.into_parts();
    let value = result.unwrap_or_else(|e| panic!("{method} response had error: {e:?}"));
    if value.is_null() {
        None
    } else {
        Some(
            serde_json::from_value(value)
                .unwrap_or_else(|e| panic!("{method} result deserialise failed: {e}")),
        )
    }
}

/// Translate a UTF-8 byte offset in `src` into the (line, UTF-16-char)
/// LSP Position used by the integration-test request bodies.
fn byte_to_line_char(src: &str, byte: usize) -> (u32, u32) {
    let mut line: u32 = 0;
    let mut col: u32 = 0; // UTF-16 code units
    let mut consumed: usize = 0;
    for c in src.chars() {
        if consumed >= byte {
            break;
        }
        if c == '\n' {
            line += 1;
            col = 0;
        } else {
            col += c.len_utf16() as u32;
        }
        consumed += c.len_utf8();
    }
    (line, col)
}

