//! Plan 03-03 Task 3 integration tests for deal-lsp.
//!
//! Drives the `Backend` through tower-lsp's `LspService` so the full
//! request → server → client pipeline is exercised. The ClientSocket
//! receiver is drained on a background task into a shared notifications
//! Vec; tests assert against that collected stream after performing the
//! relevant LSP request.
//!
//! Three required tests (one per `<behavior>` bullet in 03-03-PLAN.md):
//!
//! 1. `diagnostics_match_phase_2_codes` — open a malformed showcase file;
//!    assert publishDiagnostics arrives carrying ≥1 E-code from the
//!    Phase 2 envelope (D-32 / D-33).
//!
//! 2. `format_round_trip` — open the canonical battery.deal showcase
//!    file; send textDocument/formatting; assert returned TextEdit.new_text
//!    equals the committed golden byte-for-byte (Issue 6 — golden was
//!    generated by `deal fmt --stdout` BEFORE this test runs; the test
//!    is a regression detector, not an in-test recomputation).
//!
//! 3. `debounce_collapses_rapid_changes` — open a file, fire 5 did_change
//!    events at sub-100ms intervals, then wait past the 300ms debounce
//!    window; assert exactly two parses ran (1 for open, 1 for the
//!    coalesced re-parse).
//!
//! NOTE on showcase path: Plan 03-03-PLAN.md references
//! `tests/showcase/sedan_project/vehicle/electrical/BatteryPack.deal`,
//! which does NOT exist in this repo (Rule 3 deviation). The closest
//! match — and the canonical showcase battery model — is
//! `spec/examples/showcase/packages/vehicle/battery.deal`. Documented
//! in the Plan SUMMARY as deviation; downstream Plan 03-04 / 03-07 work
//! references this file already.

use std::time::Duration;

use deal_lsp::{Backend, Documents, Index, DEBOUNCE_MS};
use futures::StreamExt;
use std::sync::Arc;
use tokio::sync::Mutex;
use tower::Service;
use tower_lsp::jsonrpc::{Request as JsonRpcRequest, Response as JsonRpcResponse};
use tower_lsp::lsp_types::*;
use tower_lsp::LspService;

/// Path to the showcase battery.deal file (substituted for the
/// non-existent BatteryPack.deal cited in PLAN.md — see file header).
const SHOWCASE_BATTERY: &str = "../spec/examples/showcase/packages/vehicle/battery.deal";

/// Path to a known-malformed file producing E2100 codes.
const MALFORMED_SAMPLE: &str = "../tests/malformed/m01_missing_semicolon.deal";

/// Path to the showcase root (mounted via tests/showcase symlink to
/// ../spec/examples/showcase). Used as the LSP workspace folder for
/// the Plan 04 eager_parse + cross-file go-to-definition tests.
const SHOWCASE_ROOT: &str = "../spec/examples/showcase";

/// Path to the interfaces file that defines ThermallyManaged — the
/// cross-file definition target for `definition_lookup_specializes`.
/// Held as a reference constant; the test does not need to `did_open`
/// this file because the eager_parse spawned from `initialized`
/// populates the index for all workspace files automatically.
#[allow(dead_code)]
const SHOWCASE_THERMAL: &str = "../spec/examples/showcase/packages/interfaces/thermal.deal";

/// Committed golden output of `deal fmt --stdout SHOWCASE_BATTERY`.
/// Generated once by the executor during Task 3 and committed to git.
const GOLDEN_FORMATTED: &str = include_str!("golden/formatted/battery.deal.expected");

/// Committed golden output of `cargo run -p deal-lsp --bin deal-lsp-gen-golden`
/// (Plan 03-04 Task 3 / Issue 6). Read at compile time; the test does
/// byte equality on the `data` field after normalising `result_id`.
const GOLDEN_SEMANTIC_TOKENS: &str =
    include_str!("golden/semantic_tokens/BatteryPack.deal.expected.json");

/// Collected notifications (publishDiagnostics + other server-to-client
/// messages) from the LspService's ClientSocket.
type NotificationSink = Arc<Mutex<Vec<JsonRpcRequest>>>;

/// Spawn the LspService and drain ClientSocket on a background task.
/// Returns the service handle (for sending requests) and the shared
/// notification sink.
async fn spawn_service() -> (LspService<Backend>, Arc<Documents>, NotificationSink) {
    let (service, _docs, _idx, sink) = spawn_service_full().await;
    (service, _docs, sink)
}

/// Like `spawn_service` but also surfaces the Index so Plan 04 tests
/// can observe in-memory symbol-table state.
async fn spawn_service_full() -> (
    LspService<Backend>,
    Arc<Documents>,
    Arc<Index>,
    NotificationSink,
) {
    let (service, socket) = LspService::new(Backend::new);
    // Snapshot the Documents + Index Arcs so tests can introspect.
    let documents = service.inner().documents.clone();
    let index = service.inner().index.clone();

    let notifications: NotificationSink = Arc::new(Mutex::new(Vec::new()));
    {
        let sink = notifications.clone();
        tokio::spawn(async move {
            let mut socket = socket;
            while let Some(req) = socket.next().await {
                sink.lock().await.push(req);
            }
        });
    }

    (service, documents, index, notifications)
}

/// Send `initialize` so the server transitions to Initialized state
/// (otherwise tower-lsp rejects subsequent requests with "server not
/// initialized" responses).
async fn initialize(service: &mut LspService<Backend>) {
    initialize_with_root(service, None).await;
}

/// Like `initialize` but declares a workspace folder root URI so the
/// `initialized` handler kicks off the eager_parse background task
/// (Plan 03-04 Task 1).
async fn initialize_with_root(service: &mut LspService<Backend>, root: Option<&str>) {
    let workspace_folders = root.map(|p| {
        let abs = std::fs::canonicalize(p).expect("workspace root canonicalize");
        let uri = Url::from_file_path(&abs).expect("workspace folder URL");
        vec![WorkspaceFolder {
            uri,
            name: "showcase".to_string(),
        }]
    });
    let init_req = JsonRpcRequest::build("initialize")
        .id(1)
        .params(
            serde_json::to_value(InitializeParams {
                capabilities: ClientCapabilities::default(),
                workspace_folders,
                ..Default::default()
            })
            .unwrap(),
        )
        .finish();
    let _: Option<JsonRpcResponse> = service.call(init_req).await.unwrap();

    let initialized_req = JsonRpcRequest::build("initialized")
        .params(serde_json::to_value(InitializedParams {}).unwrap())
        .finish();
    let _: Option<JsonRpcResponse> = service.call(initialized_req).await.unwrap();
}

async fn did_open(service: &mut LspService<Backend>, uri: &Url, text: &str, version: i32) {
    let params = DidOpenTextDocumentParams {
        text_document: TextDocumentItem {
            uri: uri.clone(),
            language_id: "deal".to_string(),
            version,
            text: text.to_string(),
        },
    };
    let req = JsonRpcRequest::build("textDocument/didOpen")
        .params(serde_json::to_value(params).unwrap())
        .finish();
    let _: Option<JsonRpcResponse> = service.call(req).await.unwrap();
}

async fn did_change(service: &mut LspService<Backend>, uri: &Url, text: &str, version: i32) {
    let params = DidChangeTextDocumentParams {
        text_document: VersionedTextDocumentIdentifier {
            uri: uri.clone(),
            version,
        },
        content_changes: vec![TextDocumentContentChangeEvent {
            range: None,
            range_length: None,
            text: text.to_string(),
        }],
    };
    let req = JsonRpcRequest::build("textDocument/didChange")
        .params(serde_json::to_value(params).unwrap())
        .finish();
    let _: Option<JsonRpcResponse> = service.call(req).await.unwrap();
}

async fn formatting(service: &mut LspService<Backend>, uri: &Url) -> Option<Vec<TextEdit>> {
    let params = DocumentFormattingParams {
        text_document: TextDocumentIdentifier { uri: uri.clone() },
        options: FormattingOptions {
            tab_size: 4,
            insert_spaces: true,
            ..Default::default()
        },
        work_done_progress_params: Default::default(),
    };
    let req = JsonRpcRequest::build("textDocument/formatting")
        .id(99)
        .params(serde_json::to_value(params).unwrap())
        .finish();
    let resp = service
        .call(req)
        .await
        .unwrap()
        .expect("formatting returned None response");
    // resp.result() returns Option<&Value>; decode to Option<Vec<TextEdit>>.
    let (_id, result) = resp.into_parts();
    let value = result.expect("formatting response had no result");
    serde_json::from_value(value).expect("formatting result deserialise failed")
}

/// Helper: find all publishDiagnostics notifications in the sink.
async fn collected_diagnostics(sink: &NotificationSink) -> Vec<PublishDiagnosticsParams> {
    let mut out = Vec::new();
    for req in sink.lock().await.iter() {
        if req.method() == "textDocument/publishDiagnostics" {
            if let Some(params) = req.params() {
                if let Ok(p) = serde_json::from_value::<PublishDiagnosticsParams>(params.clone()) {
                    out.push(p);
                }
            }
        }
    }
    out
}

// ---------------------------------------------------------------------
// Test 1: diagnostics_match_phase_2_codes
// ---------------------------------------------------------------------

#[tokio::test]
async fn diagnostics_match_phase_2_codes() {
    let (mut service, _docs, sink) = spawn_service().await;
    initialize(&mut service).await;

    let src = std::fs::read_to_string(MALFORMED_SAMPLE).expect("malformed sample missing");
    let uri = Url::from_file_path(std::fs::canonicalize(MALFORMED_SAMPLE).unwrap())
        .expect("file:// URL build");

    did_open(&mut service, &uri, &src, 1).await;
    // Give the background sink task a moment to drain the notification.
    tokio::time::sleep(Duration::from_millis(50)).await;

    let pubs = collected_diagnostics(&sink).await;
    assert!(
        !pubs.is_empty(),
        "expected ≥1 publishDiagnostics notification after did_open"
    );
    let last = pubs.last().unwrap();
    assert_eq!(last.uri, uri);
    assert!(
        !last.diagnostics.is_empty(),
        "expected ≥1 diagnostic for malformed sample"
    );
    // Phase 2 envelope codes start with 'E' (E0xxx parser, E2xxx sema).
    let code_strs: Vec<String> = last
        .diagnostics
        .iter()
        .filter_map(|d| match &d.code {
            Some(NumberOrString::String(s)) => Some(s.clone()),
            _ => None,
        })
        .collect();
    assert!(
        code_strs.iter().any(|c| c.starts_with('E')),
        "expected at least one E-code diagnostic, got {code_strs:?}"
    );
    // Sema-level error E2100 is the expected code for this fixture
    // (verified live via dump_probe in Task 3).
    assert!(
        code_strs.iter().any(|c| c == "E2100"),
        "expected E2100 (sema undefined type) for m01 fixture, got {code_strs:?}"
    );
    // Source field must identify deal-lsp (so VS Code groups them).
    assert_eq!(last.diagnostics[0].source.as_deref(), Some("deal-lsp"));
    // Severity for the E2100 entries is ERROR.
    let has_error = last
        .diagnostics
        .iter()
        .any(|d| d.severity == Some(DiagnosticSeverity::ERROR));
    assert!(has_error, "expected at least one ERROR-severity diagnostic");
}

// ---------------------------------------------------------------------
// Test 2: format_round_trip
// ---------------------------------------------------------------------

#[tokio::test]
async fn format_round_trip() {
    let (mut service, _docs, _sink) = spawn_service().await;
    initialize(&mut service).await;

    let src = std::fs::read_to_string(SHOWCASE_BATTERY).expect("showcase battery.deal missing");
    let uri = Url::from_file_path(std::fs::canonicalize(SHOWCASE_BATTERY).unwrap())
        .expect("file:// URL build");

    did_open(&mut service, &uri, &src, 1).await;

    let edits = formatting(&mut service, &uri)
        .await
        .expect("formatting returned None for valid file");
    assert_eq!(
        edits.len(),
        1,
        "expected exactly one TextEdit covering full document"
    );

    // Byte-for-byte regression check against the committed golden.
    // If this fails: regenerate via
    //   ./target/release/deal fmt --stdout spec/examples/showcase/packages/vehicle/battery.deal \
    //     > lsp/tests/golden/formatted/battery.deal.expected
    // and re-commit. The golden is intentionally produced by the CLI
    // (an independent codepath) so the test is not a tautology
    // (Plan 03-03 Issue 6 resolution).
    assert_eq!(
        edits[0].new_text.as_bytes(),
        GOLDEN_FORMATTED.as_bytes(),
        "format_round_trip: LSP formatter output diverged from committed golden"
    );
}

// ---------------------------------------------------------------------
// Test 3: debounce_collapses_rapid_changes
// ---------------------------------------------------------------------

#[tokio::test]
async fn debounce_collapses_rapid_changes() {
    let (mut service, documents, _sink) = spawn_service().await;
    initialize(&mut service).await;

    // Synthetic in-memory source (no fs dependency).
    let uri = Url::parse("file:///debounce.deal").unwrap();
    did_open(&mut service, &uri, "package debounce;", 1).await;
    let parses_after_open = documents.parse_count();
    assert_eq!(
        parses_after_open, 1,
        "did_open should trigger exactly one parse"
    );

    // Fire 5 did_change events within the debounce window (300ms).
    for v in 2i32..=6 {
        did_change(&mut service, &uri, &format!("package debounce; // v{v}"), v).await;
        tokio::time::sleep(Duration::from_millis(30)).await;
    }
    // None of the 5 should have fired yet (only ~120ms elapsed).
    let parses_mid_burst = documents.parse_count();
    assert_eq!(
        parses_mid_burst,
        1,
        "expected 0 debounced parses during burst, got {} extra",
        parses_mid_burst - 1
    );

    // Wait comfortably past the debounce window.
    tokio::time::sleep(Duration::from_millis(DEBOUNCE_MS + 100)).await;
    let parses_after_debounce = documents.parse_count();
    assert_eq!(
        parses_after_debounce, 2,
        "expected exactly one coalesced re-parse after debounce (open=1 + debounced=1), got {parses_after_debounce}"
    );
}

// =====================================================================
// Plan 03-04 integration tests (5 new — bringing total to 8 per
// RESEARCH §1056). All exercise the providers + workspace index that
// Tasks 1–3 of Plan 04 wired up.
// =====================================================================

/// Helper: send a typed LSP request and decode the result into `T`.
async fn call_request<T: serde::de::DeserializeOwned>(
    service: &mut LspService<Backend>,
    method: &'static str,
    id: i64,
    params: impl serde::Serialize,
) -> T {
    let req = JsonRpcRequest::build(method)
        .id(id)
        .params(serde_json::to_value(params).unwrap())
        .finish();
    let resp = service
        .call(req)
        .await
        .unwrap()
        .unwrap_or_else(|| panic!("{method} returned no response"));
    let (_id, result) = resp.into_parts();
    let value = result.unwrap_or_else(|e| panic!("{method} response had error: {e:?}"));
    serde_json::from_value(value)
        .unwrap_or_else(|e| panic!("{method} result deserialise failed: {e}"))
}

/// Helper: poll `index.len()` until ≥ `threshold` or `timeout` elapses.
/// Returns the final len (so the caller can include it in failure msgs).
async fn wait_for_index(index: &Index, threshold: usize, timeout: Duration) -> usize {
    let start = std::time::Instant::now();
    while start.elapsed() < timeout {
        let n = index.len();
        if n >= threshold {
            return n;
        }
        tokio::time::sleep(Duration::from_millis(100)).await;
    }
    index.len()
}

// ---------------------------------------------------------------------
// Test 4: completion_returns_element_keywords
// ---------------------------------------------------------------------

#[tokio::test]
async fn completion_returns_element_keywords() {
    let (mut service, _docs, index, _sink) = spawn_service_full().await;
    initialize_with_root(&mut service, Some(SHOWCASE_ROOT)).await;
    // Wait for eager_parse so workspace types are available in Group 2.
    let _ = wait_for_index(&index, 20, Duration::from_secs(5)).await;

    let src = std::fs::read_to_string(SHOWCASE_BATTERY).expect("battery.deal");
    let uri = Url::from_file_path(std::fs::canonicalize(SHOWCASE_BATTERY).unwrap()).expect("URL");
    did_open(&mut service, &uri, &src, 1).await;
    tokio::time::sleep(Duration::from_millis(50)).await;

    let params = CompletionParams {
        text_document_position: TextDocumentPositionParams {
            text_document: TextDocumentIdentifier { uri: uri.clone() },
            position: Position::new(0, 0),
        },
        work_done_progress_params: WorkDoneProgressParams::default(),
        partial_result_params: PartialResultParams::default(),
        context: None,
    };
    let resp: CompletionResponse =
        call_request(&mut service, "textDocument/completion", 10, params).await;
    let items = match resp {
        CompletionResponse::Array(a) => a,
        CompletionResponse::List(l) => l.items,
    };

    // Assert all 16 element keywords are present as KEYWORD-kind items.
    let kw_labels: Vec<String> = items
        .iter()
        .filter(|i| i.kind == Some(CompletionItemKind::KEYWORD))
        .map(|i| i.label.clone())
        .collect();
    for expected in &[
        "part def",
        "port def",
        "action def",
        "state def",
        "requirement def",
        "constraint def",
        "calc def",
        "attribute def",
        "item def",
        "interface def",
        "connection def",
        "flow def",
        "allocation def",
        "need def",
        "use case def",
        "actor def",
    ] {
        assert!(
            kw_labels.iter().any(|l| l == expected),
            "missing element keyword {expected} (have: {kw_labels:?})"
        );
    }
    assert_eq!(kw_labels.len(), 16, "expected 16 element-keyword items");

    // Assert ≥3 workspace-type candidates surface as CLASS items.
    let class_items: Vec<&CompletionItem> = items
        .iter()
        .filter(|i| i.kind == Some(CompletionItemKind::CLASS))
        .collect();
    assert!(
        class_items.len() >= 3,
        "expected ≥3 workspace-type completion items, got {} (index.len = {})",
        class_items.len(),
        index.len()
    );
}

// ---------------------------------------------------------------------
// Test 5: definition_lookup_specializes
// ---------------------------------------------------------------------

#[tokio::test]
async fn definition_lookup_specializes() {
    let (mut service, _docs, index, _sink) = spawn_service_full().await;
    initialize_with_root(&mut service, Some(SHOWCASE_ROOT)).await;
    // Wait for eager_parse to populate the cross-file index.
    let n = wait_for_index(&index, 20, Duration::from_secs(5)).await;
    assert!(
        n >= 10,
        "eager_parse did not populate the index within 5s (got {n} symbols)"
    );

    // Open battery.deal — the file containing `<<specializes>> ThermallyManaged`.
    let src = std::fs::read_to_string(SHOWCASE_BATTERY).expect("battery.deal");
    let uri = Url::from_file_path(std::fs::canonicalize(SHOWCASE_BATTERY).unwrap()).unwrap();
    did_open(&mut service, &uri, &src, 1).await;
    tokio::time::sleep(Duration::from_millis(50)).await;

    // Locate the byte offset of "ThermallyManaged" in the
    // <<specializes>> clause. battery.deal mentions the type twice —
    // once in the `import` statement and once as the specializes
    // referent — we want the SECOND occurrence (the reference site).
    let needle = "ThermallyManaged";
    let first = src.find(needle).expect("ThermallyManaged in battery.deal");
    let byte = src[first + needle.len()..]
        .find(needle)
        .map(|n| first + needle.len() + n)
        .expect("second ThermallyManaged (the <<specializes>> referent)");
    let (line, char_) = byte_to_line_char(&src, byte + 4); // mid-identifier

    let params = GotoDefinitionParams {
        text_document_position_params: TextDocumentPositionParams {
            text_document: TextDocumentIdentifier { uri: uri.clone() },
            position: Position::new(line, char_),
        },
        work_done_progress_params: WorkDoneProgressParams::default(),
        partial_result_params: PartialResultParams::default(),
    };
    let resp: GotoDefinitionResponse =
        call_request_optional(&mut service, "textDocument/definition", 11, params)
            .await
            .expect(
                "textDocument/definition returned null — index lookup miss for \
         ThermallyManaged. Likely cause: eager_parse incomplete OR \
         AST candidate extraction returned None.",
            );
    let loc = match resp {
        GotoDefinitionResponse::Scalar(l) => l,
        GotoDefinitionResponse::Array(mut v) => v.pop().expect("non-empty array"),
        GotoDefinitionResponse::Link(_) => panic!("unexpected Link variant"),
    };
    // Cross-file go-to-definition: the target uri must NOT be battery.deal —
    // ThermallyManaged is defined in interfaces/thermal.deal.
    let target_path = loc.uri.to_file_path().expect("file:// URI");
    assert!(
        target_path.ends_with("interfaces/thermal.deal"),
        "expected cross-file target interfaces/thermal.deal, got {}",
        target_path.display()
    );
    // Range must be inside the target file (not empty / not bogus).
    assert!(
        loc.range.end.line >= loc.range.start.line,
        "target range is malformed: {:?}",
        loc.range
    );
}

// ---------------------------------------------------------------------
// Test 5b: references_finds_cross_file_specializes (P2 WS-A / ADR-0003)
// ---------------------------------------------------------------------

#[tokio::test]
async fn references_finds_cross_file_specializes() {
    let (mut service, _docs, index, _sink) = spawn_service_full().await;
    initialize_with_root(&mut service, Some(SHOWCASE_ROOT)).await;
    // eager_parse is two-phase (ADR-0003); wait until battery.deal's
    // <<specializes>> binding has been resolved+indexed cross-file.
    let needle_path = "interfaces.thermal.ThermallyManaged";
    let mut waited = 0;
    while index.references_of(needle_path, false).is_empty() && waited < 100 {
        tokio::time::sleep(Duration::from_millis(100)).await;
        waited += 1;
    }
    assert!(
        !index.references_of(needle_path, false).is_empty(),
        "eager_parse did not index the cross-file specializes binding within 10s"
    );

    let src = std::fs::read_to_string(SHOWCASE_BATTERY).expect("battery.deal");
    let uri = Url::from_file_path(std::fs::canonicalize(SHOWCASE_BATTERY).unwrap()).unwrap();
    did_open(&mut service, &uri, &src, 1).await;
    tokio::time::sleep(Duration::from_millis(50)).await;

    // Cursor on the <<specializes>> referent (the 2nd occurrence of the name —
    // the 1st is in the import statement).
    let nm = "ThermallyManaged";
    let first = src.find(nm).expect("ThermallyManaged in battery.deal");
    let byte = src[first + nm.len()..]
        .find(nm)
        .map(|n| first + nm.len() + n)
        .expect("second ThermallyManaged (the specializes referent)");
    let (line, char_) = byte_to_line_char(&src, byte + 4);

    let params = ReferenceParams {
        text_document_position: TextDocumentPositionParams {
            text_document: TextDocumentIdentifier { uri: uri.clone() },
            position: Position::new(line, char_),
        },
        work_done_progress_params: WorkDoneProgressParams::default(),
        partial_result_params: PartialResultParams::default(),
        context: ReferenceContext {
            include_declaration: true,
        },
    };
    let locs: Option<Vec<Location>> =
        call_request(&mut service, "textDocument/references", 12, params).await;
    let locs = locs.expect("textDocument/references returned null for ThermallyManaged");

    // The reference SITE in battery.deal must be present — this is the cross-file
    // binding ADR-0003 provides that goto-definition alone could not.
    let battery_path = std::fs::canonicalize(SHOWCASE_BATTERY).unwrap();
    assert!(
        locs.iter()
            .any(|l| l.uri.to_file_path().map(|p| p == battery_path).unwrap_or(false)),
        "find-references missing the battery.deal <<specializes>> site; got {locs:?}"
    );
    // include_declaration → the declaration in interfaces/thermal.deal is present.
    assert!(
        locs.iter().any(|l| l
            .uri
            .to_file_path()
            .map(|p| p.ends_with("interfaces/thermal.deal"))
            .unwrap_or(false)),
        "find-references missing the ThermallyManaged declaration; got {locs:?}"
    );
}

// ---------------------------------------------------------------------
// Test 5c: rename_edits_declaration_and_references (P2 WS-C)
// ---------------------------------------------------------------------

#[tokio::test]
async fn rename_edits_declaration_and_references() {
    let (mut service, _docs, index, _sink) = spawn_service_full().await;
    initialize_with_root(&mut service, Some(SHOWCASE_ROOT)).await;
    let needle_path = "interfaces.thermal.ThermallyManaged";
    let mut waited = 0;
    while index.references_of(needle_path, false).is_empty() && waited < 100 {
        tokio::time::sleep(Duration::from_millis(100)).await;
        waited += 1;
    }
    assert!(
        !index.references_of(needle_path, false).is_empty(),
        "eager_parse did not index the cross-file binding within 10s"
    );

    let src = std::fs::read_to_string(SHOWCASE_BATTERY).expect("battery.deal");
    let uri = Url::from_file_path(std::fs::canonicalize(SHOWCASE_BATTERY).unwrap()).unwrap();
    did_open(&mut service, &uri, &src, 1).await;
    tokio::time::sleep(Duration::from_millis(50)).await;

    // Cursor on the <<specializes>> referent (2nd occurrence).
    let nm = "ThermallyManaged";
    let first = src.find(nm).expect("ThermallyManaged in battery.deal");
    let byte = src[first + nm.len()..]
        .find(nm)
        .map(|n| first + nm.len() + n)
        .expect("second ThermallyManaged");
    let (line, char_) = byte_to_line_char(&src, byte + 4);

    let params = RenameParams {
        text_document_position: TextDocumentPositionParams {
            text_document: TextDocumentIdentifier { uri: uri.clone() },
            position: Position::new(line, char_),
        },
        new_name: "ThermalManaged".to_string(),
        work_done_progress_params: WorkDoneProgressParams::default(),
    };
    let edit: Option<WorkspaceEdit> =
        call_request(&mut service, "textDocument/rename", 13, params).await;
    let edit = edit.expect("rename returned null");
    let changes = edit.changes.expect("WorkspaceEdit.changes present");

    // The declaration file (interfaces/thermal.deal) AND the reference file
    // (battery.deal) must both be edited.
    assert!(
        changes.keys().any(|u| u
            .to_file_path()
            .map(|p| p.ends_with("interfaces/thermal.deal"))
            .unwrap_or(false)),
        "rename missing the ThermallyManaged declaration edit; got {:?}",
        changes.keys().collect::<Vec<_>>()
    );
    let battery_edits = changes
        .get(&uri)
        .expect("rename missing the battery.deal <<specializes>> edit");
    // Every edit replaces with the new name over a precise name-token range
    // (16 chars == "ThermallyManaged"), NOT the whole def or the `<<…>>` clause.
    for edits in changes.values() {
        for e in edits {
            assert_eq!(e.new_text, "ThermalManaged");
        }
    }
    assert!(
        battery_edits
            .iter()
            .any(|e| e.range.end.character - e.range.start.character == nm.len() as u32),
        "battery edit range is not the precise terminal-name token; got {battery_edits:?}"
    );
    // P2 WS-C import capture: rename must ALSO update the `import interfaces.{…}`
    // statement (battery.deal line 13, 0-based 12), not just the <<specializes>>
    // use — otherwise the rename leaves a dangling import and is incomplete.
    assert!(
        battery_edits.len() >= 2,
        "expected both the import-item and the <<specializes>> edit in battery.deal; got {battery_edits:?}"
    );
    assert!(
        battery_edits.iter().any(|e| e.range.start.line == 12),
        "rename did not update the `import interfaces.{{ThermallyManaged}}` statement; got {battery_edits:?}"
    );
}

// ---------------------------------------------------------------------
// Test 5d: document_symbol_outlines_file (P2 WS-D)
// ---------------------------------------------------------------------

#[tokio::test]
async fn document_symbol_outlines_file() {
    let (mut service, _docs, _idx, _sink) = spawn_service_full().await;
    initialize(&mut service).await;

    let src = std::fs::read_to_string(SHOWCASE_BATTERY).expect("battery.deal");
    let uri = Url::from_file_path(std::fs::canonicalize(SHOWCASE_BATTERY).unwrap()).unwrap();
    did_open(&mut service, &uri, &src, 1).await;
    tokio::time::sleep(Duration::from_millis(50)).await;

    let params = DocumentSymbolParams {
        text_document: TextDocumentIdentifier { uri: uri.clone() },
        work_done_progress_params: WorkDoneProgressParams::default(),
        partial_result_params: PartialResultParams::default(),
    };
    let resp: Option<DocumentSymbolResponse> =
        call_request(&mut service, "textDocument/documentSymbol", 21, params).await;
    let syms = match resp.expect("documentSymbol returned null") {
        DocumentSymbolResponse::Nested(s) => s,
        DocumentSymbolResponse::Flat(_) => panic!("expected a nested (hierarchical) outline"),
    };
    assert!(!syms.is_empty(), "outline is empty");

    // A `part def` (BatteryPack / BatteryCell) must surface as a CLASS, and at
    // least one definition must carry nested members (the outline is truly
    // hierarchical, not a flat list).
    assert!(
        syms.iter().any(|s| s.kind == SymbolKind::CLASS),
        "no part_def CLASS symbol in outline; got {syms:?}"
    );
    assert!(
        syms.iter()
            .any(|s| s.children.as_ref().map(|c| !c.is_empty()).unwrap_or(false)),
        "no definition has nested members; outline is flat: {syms:?}"
    );
}

// ---------------------------------------------------------------------
// Test 5e: signature_help_for_calc_invocation (P2 WS-E)
// ---------------------------------------------------------------------

#[tokio::test]
async fn signature_help_for_calc_invocation() {
    // The showcase has no calc invocations, so stand up a throwaway workspace
    // with one calc calling another. deal.toml is optional for discovery.
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let dir = std::env::temp_dir().join(format!("deal_sig_{}_{nanos}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let src = "package demo;\n\
        calc def Drag(rho : Real, v : Real, area : Real, cd : Real) : Real {\n\
        \x20   return rho;\n\
        }\n\
        calc def Wrap(x : Real) : Real {\n\
        \x20   return Drag(x, 2.0, 3.0, 4.0);\n\
        }\n";
    let file = dir.join("demo.deal");
    std::fs::write(&file, src).unwrap();

    let (mut service, _docs, index, _sink) = spawn_service_full().await;
    initialize_with_root(&mut service, Some(dir.to_str().unwrap())).await;

    // Wait for eager_parse to index the calc declaration.
    let mut waited = 0;
    while index.workspace_symbols("Drag").is_empty() && waited < 100 {
        tokio::time::sleep(Duration::from_millis(100)).await;
        waited += 1;
    }
    assert!(
        !index.workspace_symbols("Drag").is_empty(),
        "eager_parse did not index the calc within 10s"
    );

    let uri = Url::from_file_path(std::fs::canonicalize(&file).unwrap()).unwrap();
    did_open(&mut service, &uri, src, 1).await;
    tokio::time::sleep(Duration::from_millis(50)).await;

    // Cursor right after the first argument comma in `Drag(x, 2.0, ...)`.
    let inv = src.find("Drag(x").expect("invocation");
    let comma = src[inv..].find(',').map(|n| inv + n).expect("first arg comma");
    let (line, char_) = byte_to_line_char(src, comma + 1);

    let params = SignatureHelpParams {
        context: None,
        text_document_position_params: TextDocumentPositionParams {
            text_document: TextDocumentIdentifier { uri: uri.clone() },
            position: Position::new(line, char_),
        },
        work_done_progress_params: WorkDoneProgressParams::default(),
    };
    let help: Option<SignatureHelp> =
        call_request(&mut service, "textDocument/signatureHelp", 31, params).await;
    let _ = std::fs::remove_dir_all(&dir);

    let help = help.expect("signatureHelp returned null inside an invocation");
    let sig = &help.signatures[0];
    assert!(
        sig.label.starts_with("Drag(") && sig.label.contains("rho : Real"),
        "unexpected signature label: {}",
        sig.label
    );
    assert_eq!(
        sig.parameters.as_ref().map(|p| p.len()),
        Some(4),
        "expected 4 parameters"
    );
    // Cursor is after the first comma → second parameter is active.
    assert_eq!(help.active_parameter, Some(1));
}

// ---------------------------------------------------------------------
// Test 5f: code_action_suggests_nearest_symbol (P2 WS-F)
// ---------------------------------------------------------------------

#[tokio::test]
async fn code_action_suggests_nearest_symbol() {
    // Throwaway workspace: a correct decl + a typo'd <<specializes>> target,
    // which fires E2000 (name not found). The quick-fix should offer the
    // correct symbol by edit distance.
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let dir = std::env::temp_dir().join(format!("deal_ca_{}_{nanos}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let src = "package demo;\n\
        interface def ThermallyManaged { }\n\
        part def Pack <<specializes>> ThermallyManagd { }\n";
    let file = dir.join("demo.deal");
    std::fs::write(&file, src).unwrap();

    let (mut service, _docs, index, sink) = spawn_service_full().await;
    initialize_with_root(&mut service, Some(dir.to_str().unwrap())).await;
    let mut waited = 0;
    while index.workspace_symbols("ThermallyManaged").is_empty() && waited < 100 {
        tokio::time::sleep(Duration::from_millis(100)).await;
        waited += 1;
    }

    let uri = Url::from_file_path(std::fs::canonicalize(&file).unwrap()).unwrap();
    did_open(&mut service, &uri, src, 1).await;
    tokio::time::sleep(Duration::from_millis(50)).await;

    // Pull the real E2000 diagnostic the server published.
    let pubs = collected_diagnostics(&sink).await;
    let diag = pubs
        .iter()
        .filter(|p| p.uri == uri)
        .flat_map(|p| p.diagnostics.iter())
        .find(|d| matches!(&d.code, Some(NumberOrString::String(c)) if c == "E2000"))
        .cloned();
    let diag = diag.expect("expected an E2000 diagnostic for the typo'd specializes target");

    let params = CodeActionParams {
        text_document: TextDocumentIdentifier { uri: uri.clone() },
        range: diag.range,
        context: CodeActionContext {
            diagnostics: vec![diag.clone()],
            only: None,
            trigger_kind: None,
        },
        work_done_progress_params: WorkDoneProgressParams::default(),
        partial_result_params: PartialResultParams::default(),
    };
    let resp: Option<CodeActionResponse> =
        call_request(&mut service, "textDocument/codeAction", 41, params).await;
    let _ = std::fs::remove_dir_all(&dir);

    let actions = resp.expect("codeAction returned null");
    let action = actions
        .iter()
        .find_map(|a| match a {
            CodeActionOrCommand::CodeAction(ca) => Some(ca),
            _ => None,
        })
        .expect("expected a CodeAction quick-fix");
    assert!(
        action.title.contains("ThermallyManaged"),
        "unexpected action title: {}",
        action.title
    );
    // The edit replaces exactly the typo'd name with the correct symbol.
    let edits = action
        .edit
        .as_ref()
        .and_then(|e| e.changes.as_ref())
        .and_then(|c| c.get(&uri))
        .expect("quick-fix edits the document");
    assert_eq!(edits.len(), 1);
    assert_eq!(edits[0].new_text, "ThermallyManaged");
    let width = edits[0].range.end.character - edits[0].range.start.character;
    assert_eq!(
        width,
        "ThermallyManagd".len() as u32,
        "edit should replace only the typo'd name token"
    );
}

// ---------------------------------------------------------------------
// Test 5g: definition_jumps_to_parameter (P2 WS-E2)
// ---------------------------------------------------------------------

#[tokio::test]
async fn definition_jumps_to_parameter() {
    // Throwaway workspace with a calc referencing its parameter in the body.
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let dir = std::env::temp_dir().join(format!("deal_param_{}_{nanos}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let src = "package demo;\n\
        calc def Scale(factor : Real) : Real {\n\
        \x20   return factor * 2.0;\n\
        }\n";
    let file = dir.join("demo.deal");
    std::fs::write(&file, src).unwrap();

    let (mut service, _docs, index, _sink) = spawn_service_full().await;
    initialize_with_root(&mut service, Some(dir.to_str().unwrap())).await;
    let mut waited = 0;
    while index.workspace_symbols("Scale").is_empty() && waited < 100 {
        tokio::time::sleep(Duration::from_millis(100)).await;
        waited += 1;
    }

    let uri = Url::from_file_path(std::fs::canonicalize(&file).unwrap()).unwrap();
    did_open(&mut service, &uri, src, 1).await;
    tokio::time::sleep(Duration::from_millis(50)).await;

    // Cursor on `factor` in `return factor * 2.0` (the body reference, line 2).
    let decl_off = src.find("factor").expect("param decl");
    let body_off = src[decl_off + 6..]
        .find("factor")
        .map(|n| decl_off + 6 + n)
        .expect("body reference");
    let (line, char_) = byte_to_line_char(src, body_off + 2);

    let params = GotoDefinitionParams {
        text_document_position_params: TextDocumentPositionParams {
            text_document: TextDocumentIdentifier { uri: uri.clone() },
            position: Position::new(line, char_),
        },
        work_done_progress_params: WorkDoneProgressParams::default(),
        partial_result_params: PartialResultParams::default(),
    };
    let resp: Option<GotoDefinitionResponse> =
        call_request(&mut service, "textDocument/definition", 51, params).await;
    let _ = std::fs::remove_dir_all(&dir);

    let loc = match resp.expect("definition returned null") {
        GotoDefinitionResponse::Scalar(l) => l,
        other => panic!("expected a scalar location, got {other:?}"),
    };
    assert_eq!(loc.uri, uri);
    // The declaration is on the calc-def line (1), above the body reference (2).
    let (decl_line, _) = byte_to_line_char(src, decl_off);
    assert_eq!(
        loc.range.start.line, decl_line,
        "goto-def should land on the parameter declaration, not the body reference"
    );
    assert!(
        loc.range.start.line < line,
        "resolved location must be the decl (earlier line) not the reference"
    );
}

// ---------------------------------------------------------------------
// Test 5h: folding_ranges_for_definitions (P3 WS-C C1)
// ---------------------------------------------------------------------

#[tokio::test]
async fn folding_ranges_for_definitions() {
    let (mut service, _docs, _idx, _sink) = spawn_service_full().await;
    initialize(&mut service).await;

    let src = std::fs::read_to_string(SHOWCASE_BATTERY).expect("battery.deal");
    let uri = Url::from_file_path(std::fs::canonicalize(SHOWCASE_BATTERY).unwrap()).unwrap();
    did_open(&mut service, &uri, &src, 1).await;
    tokio::time::sleep(Duration::from_millis(50)).await;

    let params = FoldingRangeParams {
        text_document: TextDocumentIdentifier { uri: uri.clone() },
        work_done_progress_params: WorkDoneProgressParams::default(),
        partial_result_params: PartialResultParams::default(),
    };
    let ranges: Option<Vec<FoldingRange>> =
        call_request(&mut service, "textDocument/foldingRange", 61, params).await;
    let ranges = ranges.expect("foldingRange returned null");
    assert!(!ranges.is_empty(), "expected folds for a multi-def file");
    // Every fold spans more than one line.
    assert!(
        ranges.iter().all(|r| r.end_line > r.start_line),
        "a fold collapsed to a single line: {ranges:?}"
    );
    // battery.deal has /** … */ doc comments → at least one Comment-kind fold.
    assert!(
        ranges
            .iter()
            .any(|r| r.kind == Some(FoldingRangeKind::Comment)),
        "expected at least one doc-comment fold; got {ranges:?}"
    );
}

// ---------------------------------------------------------------------
// Test 5i: inlay_hints_show_metaclass_badges (P3 WS-C C2)
// ---------------------------------------------------------------------

#[tokio::test]
async fn inlay_hints_show_metaclass_badges() {
    let (mut service, _docs, index, _sink) = spawn_service_full().await;
    initialize_with_root(&mut service, Some(SHOWCASE_ROOT)).await;

    let uri = Url::from_file_path(std::fs::canonicalize(SHOWCASE_BATTERY).unwrap()).unwrap();
    let mut waited = 0;
    while index.elements_in_file(&uri).is_empty() && waited < 100 {
        tokio::time::sleep(Duration::from_millis(100)).await;
        waited += 1;
    }
    assert!(
        !index.elements_in_file(&uri).is_empty(),
        "eager_parse did not index battery.deal elements within 10s"
    );

    let src = std::fs::read_to_string(SHOWCASE_BATTERY).expect("battery.deal");
    let last_line = src.lines().count() as u32 + 1;
    let params = InlayHintParams {
        text_document: TextDocumentIdentifier { uri: uri.clone() },
        range: Range {
            start: Position::new(0, 0),
            end: Position::new(last_line, 0),
        },
        work_done_progress_params: WorkDoneProgressParams::default(),
    };
    let hints: Option<Vec<InlayHint>> =
        call_request(&mut service, "textDocument/inlayHint", 71, params).await;
    let hints = hints.expect("inlayHint returned null");
    assert!(!hints.is_empty(), "expected metaclass badge hints");
    // BatteryPack/BatteryCell/BatteryModule are `part def`s → «PartDefinition».
    assert!(
        hints
            .iter()
            .any(|h| matches!(&h.label, InlayHintLabel::String(s) if s == "«PartDefinition»")),
        "no «PartDefinition» badge among inlay hints: {hints:?}"
    );
}

// ---------------------------------------------------------------------
// Test 5j: code_lens_reference_counts (P3 WS-C C3)
// ---------------------------------------------------------------------

#[tokio::test]
async fn code_lens_reference_counts() {
    let (mut service, _docs, index, _sink) = spawn_service_full().await;
    initialize_with_root(&mut service, Some(SHOWCASE_ROOT)).await;

    let uri = Url::from_file_path(std::fs::canonicalize(SHOWCASE_BATTERY).unwrap()).unwrap();
    let mut waited = 0;
    while index.elements_in_file(&uri).is_empty() && waited < 100 {
        tokio::time::sleep(Duration::from_millis(100)).await;
        waited += 1;
    }

    let params = CodeLensParams {
        text_document: TextDocumentIdentifier { uri: uri.clone() },
        work_done_progress_params: WorkDoneProgressParams::default(),
        partial_result_params: PartialResultParams::default(),
    };
    let lenses: Option<Vec<CodeLens>> =
        call_request(&mut service, "textDocument/codeLens", 81, params).await;
    let lenses = lenses.expect("codeLens returned null");
    assert!(!lenses.is_empty(), "expected reference-count lenses on definitions");
    // Every lens routes through the extension bridge command.
    assert!(
        lenses
            .iter()
            .all(|l| l.command.as_ref().is_some_and(|c| c.command == "deal.showReferences")),
        "a lens used the wrong command: {lenses:?}"
    );
    // At least one definition has ≥1 reference (e.g. BatteryCell used in
    // BatteryModule) — proves the count is sourced from the real index.
    assert!(
        lenses.iter().any(|l| l
            .command
            .as_ref()
            .and_then(|c| c.title.chars().next())
            .is_some_and(|d| d.is_ascii_digit() && d != '0')),
        "expected at least one declaration with a non-zero reference count: {lenses:?}"
    );
}

// ---------------------------------------------------------------------
// Test 5k: document_links_for_imports (P3 WS-C C4)
// ---------------------------------------------------------------------

#[tokio::test]
async fn document_links_for_imports() {
    let (mut service, _docs, index, _sink) = spawn_service_full().await;
    initialize_with_root(&mut service, Some(SHOWCASE_ROOT)).await;

    let uri = Url::from_file_path(std::fs::canonicalize(SHOWCASE_BATTERY).unwrap()).unwrap();
    let mut waited = 0;
    while index.import_links_in_file(&uri).is_empty() && waited < 100 {
        tokio::time::sleep(Duration::from_millis(100)).await;
        waited += 1;
    }
    assert!(
        !index.import_links_in_file(&uri).is_empty(),
        "eager_parse did not index battery.deal import links within 10s"
    );

    let params = DocumentLinkParams {
        text_document: TextDocumentIdentifier { uri: uri.clone() },
        work_done_progress_params: WorkDoneProgressParams::default(),
        partial_result_params: PartialResultParams::default(),
    };
    let links: Option<Vec<DocumentLink>> =
        call_request(&mut service, "textDocument/documentLink", 91, params).await;
    let links = links.expect("documentLink returned null");
    assert!(!links.is_empty(), "expected document links on the import statement");
    // `import interfaces.{… ThermallyManaged …}` links to the declaring file.
    assert!(
        links.iter().any(|l| l
            .target
            .as_ref()
            .is_some_and(|t| t.path().ends_with("interfaces/thermal.deal"))),
        "no import link targets interfaces/thermal.deal: {links:?}"
    );
}

// ---------------------------------------------------------------------
// Test 6: hover_renders_jsdoc
// ---------------------------------------------------------------------

#[tokio::test]
async fn hover_renders_jsdoc() {
    let (mut service, _docs, _idx, _sink) = spawn_service_full().await;
    initialize(&mut service).await;

    let src = std::fs::read_to_string(SHOWCASE_BATTERY).expect("battery.deal");
    let uri = Url::from_file_path(std::fs::canonicalize(SHOWCASE_BATTERY).unwrap()).unwrap();
    did_open(&mut service, &uri, &src, 1).await;
    tokio::time::sleep(Duration::from_millis(50)).await;

    // battery.deal line 22 (0-based 21): `part def BatteryCell {` — has a
    // /** ... */ doc comment immediately above it covering "Individual
    // lithium-ion pouch cell." Hover on "BatteryCell" identifier.
    let needle = "part def BatteryCell";
    let byte = src
        .find(needle)
        .expect("BatteryCell declaration in battery.deal");
    // Position cursor INSIDE the part_def span (e.g. on "def").
    let (line, char_) = byte_to_line_char(&src, byte + 5);

    let params = HoverParams {
        text_document_position_params: TextDocumentPositionParams {
            text_document: TextDocumentIdentifier { uri: uri.clone() },
            position: Position::new(line, char_),
        },
        work_done_progress_params: WorkDoneProgressParams::default(),
    };
    let resp: Option<Hover> =
        call_request_optional(&mut service, "textDocument/hover", 12, params).await;
    let hover = resp.expect("hover returned None for documented declaration");
    let markup = match hover.contents {
        HoverContents::Markup(m) => m,
        _ => panic!("expected Markup hover contents"),
    };
    assert_eq!(markup.kind, MarkupKind::Markdown);
    assert!(
        markup.value.contains("Individual lithium-ion pouch cell"),
        "hover markup missing expected doc text; got: {:?}",
        markup.value
    );
}

// ---------------------------------------------------------------------
// Test 7: semantic_tokens_match_golden
// ---------------------------------------------------------------------

#[tokio::test]
async fn semantic_tokens_match_golden() {
    let (mut service, _docs, _idx, _sink) = spawn_service_full().await;
    initialize(&mut service).await;

    let src = std::fs::read_to_string(SHOWCASE_BATTERY).expect("battery.deal");
    let uri = Url::from_file_path(std::fs::canonicalize(SHOWCASE_BATTERY).unwrap()).unwrap();
    did_open(&mut service, &uri, &src, 1).await;
    tokio::time::sleep(Duration::from_millis(50)).await;

    let params = SemanticTokensParams {
        text_document: TextDocumentIdentifier { uri: uri.clone() },
        work_done_progress_params: WorkDoneProgressParams::default(),
        partial_result_params: PartialResultParams::default(),
    };
    let resp: SemanticTokensResult =
        call_request(&mut service, "textDocument/semanticTokens/full", 13, params).await;
    let actual = match resp {
        SemanticTokensResult::Tokens(t) => t,
        SemanticTokensResult::Partial(_) => panic!("expected Tokens variant"),
    };

    // Issue 6 resolution: parse the committed golden via serde_json and
    // compare only the `data` field byte-for-byte. result_id differs
    // (golden: "golden"; runtime: per-session UUID) — normalize away.
    let golden: SemanticTokens =
        serde_json::from_str(GOLDEN_SEMANTIC_TOKENS).expect("golden JSON parse");
    assert_eq!(
        actual.data, golden.data,
        "semantic-tokens data drift — regenerate via: \
         cargo run --release -p deal-lsp --bin deal-lsp-gen-golden -- \
         tests/showcase/packages/vehicle/battery.deal \
         lsp/tests/golden/semantic_tokens/BatteryPack.deal.expected.json \
         and re-commit the golden file (Issue 6 — no inline env-var \
         escape hatch in this test source)."
    );
}

// ---------------------------------------------------------------------
// Test 8: workspace_index_populated_after_initialize
// ---------------------------------------------------------------------

#[tokio::test]
async fn workspace_index_populated_after_initialize() {
    let (mut service, _docs, index, _sink) = spawn_service_full().await;
    initialize_with_root(&mut service, Some(SHOWCASE_ROOT)).await;

    // Poll up to 5s for the eager_parse background task to finish.
    // Threshold: the showcase has 19 .deal/.dealx files producing ≥40
    // FQ-path entries (measured empirically: 48 at the time of authoring).
    // We use 40 to leave headroom for showcase-edit drift while still
    // proving eager_parse actually executed (not just spun up).
    let n = wait_for_index(&index, 40, Duration::from_secs(5)).await;
    assert!(
        n >= 40,
        "eager_parse should populate ≥40 symbols on the showcase, got {n}"
    );
    // Spot-check: ThermallyManaged + BatteryPack are showcase staples;
    // they must be in the in-memory index under SOME PathString. The
    // exact prefix depends on which file declared which `package`
    // statement — we accept any path whose suffix matches the type name.
    let snap = index.snapshot();
    let paths: Vec<String> = snap.iter().map(|(p, _)| p.clone()).collect();
    let has_suffix = |needle: &str| -> bool {
        paths
            .iter()
            .any(|p| p == needle || p.ends_with(&format!(".{needle}")))
    };
    assert!(
        has_suffix("ThermallyManaged"),
        "expected an index entry ending in .ThermallyManaged. Top paths: {:?}",
        &paths[..paths.len().min(10)]
    );
    assert!(
        has_suffix("BatteryPack"),
        "expected an index entry ending in .BatteryPack. Top paths: {:?}",
        &paths[..paths.len().min(10)]
    );
}

// ---------------------------------------------------------------------
// Helpers used by the 5 Plan 04 tests above
// ---------------------------------------------------------------------

/// Helper for requests whose result type is `Option<T>` (e.g. hover).
async fn call_request_optional<T: serde::de::DeserializeOwned>(
    service: &mut LspService<Backend>,
    method: &'static str,
    id: i64,
    params: impl serde::Serialize,
) -> Option<T> {
    let req = JsonRpcRequest::build(method)
        .id(id)
        .params(serde_json::to_value(params).unwrap())
        .finish();
    let resp = service
        .call(req)
        .await
        .unwrap()
        .unwrap_or_else(|| panic!("{method} returned no response"));
    let (_id, result) = resp.into_parts();
    let value = result.unwrap_or_else(|e| panic!("{method} response had error: {e:?}"));
    if value.is_null() {
        None
    } else {
        Some(
            serde_json::from_value(value)
                .unwrap_or_else(|e| panic!("{method} result deserialise failed: {e}")),
        )
    }
}

/// Translate a UTF-8 byte offset in `src` into the (line, UTF-16-char)
/// LSP Position used by the integration-test request bodies.
fn byte_to_line_char(src: &str, byte: usize) -> (u32, u32) {
    let mut line: u32 = 0;
    let mut col: u32 = 0; // UTF-16 code units
    let mut consumed: usize = 0;
    for c in src.chars() {
        if consumed >= byte {
            break;
        }
        if c == '\n' {
            line += 1;
            col = 0;
        } else {
            col += c.len_utf16() as u32;
        }
        consumed += c.len_utf8();
    }
    (line, col)
}
